[package]
name = "lradc_check"
version = "0.1.0"
edition = "2021"

[dependencies]
evdev = "=0.12.2"
axum = { version = "0.7", features = ["ws"] } 
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "time", "sync"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"